spring:
  application:
    name: MoneyFi-notification
  profiles:
    active: ${PROFILE:local}

email:
  filter:
    from:
      email : ${ADMIN_EMAIL}
      password : ${ADMIN_PASSWORD}

jwt:
  secret: ekhfjulewfsuydg342fhdarewugafhs69aufg7efesdaf

server:
  port: 8600